# Welcome to Jekyll!
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

# Theme Settings
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "ko-KR"
rtl: false
title: "mings code note"
title_separator: "|"
subtitle: "small positive action"
name: "mings code note"
description: "공부 정리용 git blog."
url: "https://mingcode123.github.io"
baseurl: ""
repository: "mingscode123/repo-name" # GitHub repository 추가
teaser: ""
logo: "/assets/images/덕선프로필.png"
masthead_title:
breadcrumbs: true
words_per_minute: 200
enable_copy_code_button: false
copyright: "mings code note"
copyright_url: "https://mingcode123.github.io"

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: G-Q8SCC3XWGN
    anonymize_ip:

# Comments
comments:
  provider: "disqus"
  disqus:
    shortname: "mingscodenote"
  discourse:
    server: ""
  facebook:
    appid: ""
    num_posts: 5
    colorscheme: "light"
  utterances:
    theme: "github-light"
    issue_term: "pathname"
  giscus:
    repo_id: ""
    category_name: ""
    category_id: ""
    discussion_term: "pathname"
    reactions_enabled: "1"
    theme: "light"
    input_position: "bottom"
    lang: "en"
    lazy: true

# reCaptcha
reCaptcha:
  siteKey:
  secret:

# Atom Feed
atom_feed:
  path: feed.xml
  hide: false

# Search
search: true
search_full_content: false
search_provider: lunr
lunr:
  search_within_pages: true
algolia:
  application_id: ""
  index_name: ""
  search_only_api_key: ""
  powered_by: true
google:
  search_engine_id: ""
  instant_search: false

# SEO Related
google_site_verification:
bing_site_verification:
naver_site_verification: "fa0622a67d866dbac6db8122b63d214534cf7630"
yandex_site_verification:
baidu_site_verification:

# Social Sharing
twitter:
  username: ""
facebook:
  username: ""
  app_id: ""
  publisher: ""
og_image: ""

# Social profiles
social:
  type: "Person"
  name: "mings code note"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mingscode123"
    - label: "Twitter" # 추가된 소셜 링크 예시
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/your-handle"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/your-profile"

# Site Author
author:
  name: "mings code note"
  avatar: "/assets/images/덕선프로필.png"
  bio: "공부 정리용 git blog"
  location: "South Korea"
  email: "gomgomi09@gmail.com"
  links:
  
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mingscode123"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mingscode123"
    - label: "Twitter" # 추가된 소셜 링크 예시
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/your-handle"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/your-profile"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
timezone: "Asia/Seoul"

# Pagination with jekyll-paginate
paginate: 5
paginate_path: /page:num/

# Pagination with jekyll-paginate-v2
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      date_format: "%Y-%m-%d"
